/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SegmentosRouteImport } from './routes/segmentos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecursosRouteImport } from './routes/recursos'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AgendarSlugRouteImport } from './routes/agendar.$slug'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated/whatsapp'
import { Route as AuthenticatedWaInboxRouteImport } from './routes/_authenticated/wa-inbox'
import { Route as AuthenticatedWaConfigRouteImport } from './routes/_authenticated/wa-config'
import { Route as AuthenticatedVendasRouteImport } from './routes/_authenticated/vendas'
import { Route as AuthenticatedSuperAdminRouteImport } from './routes/_authenticated/super-admin'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedPlanejamentoRouteImport } from './routes/_authenticated/planejamento'
import { Route as AuthenticatedPdvRouteImport } from './routes/_authenticated/pdv'
import { Route as AuthenticatedOsRouteImport } from './routes/_authenticated/os'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedLojaPropriaRouteImport } from './routes/_authenticated/loja-propria'
import { Route as AuthenticatedIntegracoesRouteImport } from './routes/_authenticated/integracoes'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedIaRouteImport } from './routes/_authenticated/ia'
import { Route as AuthenticatedHojeRouteImport } from './routes/_authenticated/hoje'
import { Route as AuthenticatedGuiaRouteImport } from './routes/_authenticated/guia'
import { Route as AuthenticatedFunilRouteImport } from './routes/_authenticated/funil'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCaixaRouteImport } from './routes/_authenticated/caixa'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedOsIdRouteImport } from './routes/_authenticated/os.$id'
import { Route as AuthenticatedCrmIdRouteImport } from './routes/_authenticated/crm.$id'
import { Route as ApiPublicWaWebhookRouteImport } from './routes/api/public/wa.webhook'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentosRoute = SegmentosRouteImport.update({
  id: '/segmentos',
  path: '/segmentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosRoute = RecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarSlugRoute = AgendarSlugRouteImport.update({
  id: '/agendar/$slug',
  path: '/agendar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWaInboxRoute = AuthenticatedWaInboxRouteImport.update({
  id: '/wa-inbox',
  path: '/wa-inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWaConfigRoute = AuthenticatedWaConfigRouteImport.update({
  id: '/wa-config',
  path: '/wa-config',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendasRoute = AuthenticatedVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuperAdminRoute = AuthenticatedSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanejamentoRoute =
  AuthenticatedPlanejamentoRouteImport.update({
    id: '/planejamento',
    path: '/planejamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPdvRoute = AuthenticatedPdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOsRoute = AuthenticatedOsRouteImport.update({
  id: '/os',
  path: '/os',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLojaPropriaRoute =
  AuthenticatedLojaPropriaRouteImport.update({
    id: '/loja-propria',
    path: '/loja-propria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntegracoesRoute =
  AuthenticatedIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIaRoute = AuthenticatedIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHojeRoute = AuthenticatedHojeRouteImport.update({
  id: '/hoje',
  path: '/hoje',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuiaRoute = AuthenticatedGuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFunilRoute = AuthenticatedFunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCaixaRoute = AuthenticatedCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOsIdRoute = AuthenticatedOsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedOsRoute,
} as any)
const AuthenticatedCrmIdRoute = AuthenticatedCrmIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const ApiPublicWaWebhookRoute = ApiPublicWaWebhookRouteImport.update({
  id: '/api/public/wa/webhook',
  path: '/api/public/wa/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/precos': typeof PrecosRoute
  '/recursos': typeof RecursosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/segmentos': typeof SegmentosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/crm': typeof AuthenticatedCrmRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/funil': typeof AuthenticatedFunilRoute
  '/guia': typeof AuthenticatedGuiaRoute
  '/hoje': typeof AuthenticatedHojeRoute
  '/ia': typeof AuthenticatedIaRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/loja-propria': typeof AuthenticatedLojaPropriaRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/os': typeof AuthenticatedOsRouteWithChildren
  '/pdv': typeof AuthenticatedPdvRoute
  '/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/super-admin': typeof AuthenticatedSuperAdminRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/wa-config': typeof AuthenticatedWaConfigRoute
  '/wa-inbox': typeof AuthenticatedWaInboxRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/agendar/$slug': typeof AgendarSlugRoute
  '/api/chat': typeof ApiChatRoute
  '/crm/$id': typeof AuthenticatedCrmIdRoute
  '/os/$id': typeof AuthenticatedOsIdRoute
  '/api/public/wa/webhook': typeof ApiPublicWaWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/precos': typeof PrecosRoute
  '/recursos': typeof RecursosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/segmentos': typeof SegmentosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/crm': typeof AuthenticatedCrmRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/funil': typeof AuthenticatedFunilRoute
  '/guia': typeof AuthenticatedGuiaRoute
  '/hoje': typeof AuthenticatedHojeRoute
  '/ia': typeof AuthenticatedIaRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/loja-propria': typeof AuthenticatedLojaPropriaRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/os': typeof AuthenticatedOsRouteWithChildren
  '/pdv': typeof AuthenticatedPdvRoute
  '/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/super-admin': typeof AuthenticatedSuperAdminRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/wa-config': typeof AuthenticatedWaConfigRoute
  '/wa-inbox': typeof AuthenticatedWaInboxRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/agendar/$slug': typeof AgendarSlugRoute
  '/api/chat': typeof ApiChatRoute
  '/crm/$id': typeof AuthenticatedCrmIdRoute
  '/os/$id': typeof AuthenticatedOsIdRoute
  '/api/public/wa/webhook': typeof ApiPublicWaWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/precos': typeof PrecosRoute
  '/recursos': typeof RecursosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/segmentos': typeof SegmentosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/caixa': typeof AuthenticatedCaixaRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/funil': typeof AuthenticatedFunilRoute
  '/_authenticated/guia': typeof AuthenticatedGuiaRoute
  '/_authenticated/hoje': typeof AuthenticatedHojeRoute
  '/_authenticated/ia': typeof AuthenticatedIaRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/integracoes': typeof AuthenticatedIntegracoesRoute
  '/_authenticated/loja-propria': typeof AuthenticatedLojaPropriaRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/os': typeof AuthenticatedOsRouteWithChildren
  '/_authenticated/pdv': typeof AuthenticatedPdvRoute
  '/_authenticated/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/super-admin': typeof AuthenticatedSuperAdminRoute
  '/_authenticated/vendas': typeof AuthenticatedVendasRoute
  '/_authenticated/wa-config': typeof AuthenticatedWaConfigRoute
  '/_authenticated/wa-inbox': typeof AuthenticatedWaInboxRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
  '/agendar/$slug': typeof AgendarSlugRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/crm/$id': typeof AuthenticatedCrmIdRoute
  '/_authenticated/os/$id': typeof AuthenticatedOsIdRoute
  '/api/public/wa/webhook': typeof ApiPublicWaWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contato'
    | '/precos'
    | '/recursos'
    | '/reset-password'
    | '/segmentos'
    | '/sitemap.xml'
    | '/agenda'
    | '/caixa'
    | '/configuracoes'
    | '/crm'
    | '/dashboard'
    | '/equipe'
    | '/estoque'
    | '/financeiro'
    | '/funil'
    | '/guia'
    | '/hoje'
    | '/ia'
    | '/inicio'
    | '/integracoes'
    | '/loja-propria'
    | '/onboarding'
    | '/os'
    | '/pdv'
    | '/planejamento'
    | '/relatorios'
    | '/super-admin'
    | '/vendas'
    | '/wa-config'
    | '/wa-inbox'
    | '/whatsapp'
    | '/agendar/$slug'
    | '/api/chat'
    | '/crm/$id'
    | '/os/$id'
    | '/api/public/wa/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contato'
    | '/precos'
    | '/recursos'
    | '/reset-password'
    | '/segmentos'
    | '/sitemap.xml'
    | '/agenda'
    | '/caixa'
    | '/configuracoes'
    | '/crm'
    | '/dashboard'
    | '/equipe'
    | '/estoque'
    | '/financeiro'
    | '/funil'
    | '/guia'
    | '/hoje'
    | '/ia'
    | '/inicio'
    | '/integracoes'
    | '/loja-propria'
    | '/onboarding'
    | '/os'
    | '/pdv'
    | '/planejamento'
    | '/relatorios'
    | '/super-admin'
    | '/vendas'
    | '/wa-config'
    | '/wa-inbox'
    | '/whatsapp'
    | '/agendar/$slug'
    | '/api/chat'
    | '/crm/$id'
    | '/os/$id'
    | '/api/public/wa/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contato'
    | '/precos'
    | '/recursos'
    | '/reset-password'
    | '/segmentos'
    | '/sitemap.xml'
    | '/_authenticated/agenda'
    | '/_authenticated/caixa'
    | '/_authenticated/configuracoes'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/equipe'
    | '/_authenticated/estoque'
    | '/_authenticated/financeiro'
    | '/_authenticated/funil'
    | '/_authenticated/guia'
    | '/_authenticated/hoje'
    | '/_authenticated/ia'
    | '/_authenticated/inicio'
    | '/_authenticated/integracoes'
    | '/_authenticated/loja-propria'
    | '/_authenticated/onboarding'
    | '/_authenticated/os'
    | '/_authenticated/pdv'
    | '/_authenticated/planejamento'
    | '/_authenticated/relatorios'
    | '/_authenticated/super-admin'
    | '/_authenticated/vendas'
    | '/_authenticated/wa-config'
    | '/_authenticated/wa-inbox'
    | '/_authenticated/whatsapp'
    | '/agendar/$slug'
    | '/api/chat'
    | '/_authenticated/crm/$id'
    | '/_authenticated/os/$id'
    | '/api/public/wa/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContatoRoute: typeof ContatoRoute
  PrecosRoute: typeof PrecosRoute
  RecursosRoute: typeof RecursosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SegmentosRoute: typeof SegmentosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AgendarSlugRoute: typeof AgendarSlugRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicWaWebhookRoute: typeof ApiPublicWaWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos': {
      id: '/segmentos'
      path: '/segmentos'
      fullPath: '/segmentos'
      preLoaderRoute: typeof SegmentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos': {
      id: '/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof RecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar/$slug': {
      id: '/agendar/$slug'
      path: '/agendar/$slug'
      fullPath: '/agendar/$slug'
      preLoaderRoute: typeof AgendarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wa-inbox': {
      id: '/_authenticated/wa-inbox'
      path: '/wa-inbox'
      fullPath: '/wa-inbox'
      preLoaderRoute: typeof AuthenticatedWaInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wa-config': {
      id: '/_authenticated/wa-config'
      path: '/wa-config'
      fullPath: '/wa-config'
      preLoaderRoute: typeof AuthenticatedWaConfigRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas': {
      id: '/_authenticated/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AuthenticatedVendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin': {
      id: '/_authenticated/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof AuthenticatedSuperAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planejamento': {
      id: '/_authenticated/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof AuthenticatedPlanejamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pdv': {
      id: '/_authenticated/pdv'
      path: '/pdv'
      fullPath: '/pdv'
      preLoaderRoute: typeof AuthenticatedPdvRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/os': {
      id: '/_authenticated/os'
      path: '/os'
      fullPath: '/os'
      preLoaderRoute: typeof AuthenticatedOsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loja-propria': {
      id: '/_authenticated/loja-propria'
      path: '/loja-propria'
      fullPath: '/loja-propria'
      preLoaderRoute: typeof AuthenticatedLojaPropriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integracoes': {
      id: '/_authenticated/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof AuthenticatedIntegracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ia': {
      id: '/_authenticated/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof AuthenticatedIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hoje': {
      id: '/_authenticated/hoje'
      path: '/hoje'
      fullPath: '/hoje'
      preLoaderRoute: typeof AuthenticatedHojeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guia': {
      id: '/_authenticated/guia'
      path: '/guia'
      fullPath: '/guia'
      preLoaderRoute: typeof AuthenticatedGuiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/funil': {
      id: '/_authenticated/funil'
      path: '/funil'
      fullPath: '/funil'
      preLoaderRoute: typeof AuthenticatedFunilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caixa': {
      id: '/_authenticated/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof AuthenticatedCaixaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/os/$id': {
      id: '/_authenticated/os/$id'
      path: '/$id'
      fullPath: '/os/$id'
      preLoaderRoute: typeof AuthenticatedOsIdRouteImport
      parentRoute: typeof AuthenticatedOsRoute
    }
    '/_authenticated/crm/$id': {
      id: '/_authenticated/crm/$id'
      path: '/$id'
      fullPath: '/crm/$id'
      preLoaderRoute: typeof AuthenticatedCrmIdRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/api/public/wa/webhook': {
      id: '/api/public/wa/webhook'
      path: '/api/public/wa/webhook'
      fullPath: '/api/public/wa/webhook'
      preLoaderRoute: typeof ApiPublicWaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedCrmRouteChildren {
  AuthenticatedCrmIdRoute: typeof AuthenticatedCrmIdRoute
}

const AuthenticatedCrmRouteChildren: AuthenticatedCrmRouteChildren = {
  AuthenticatedCrmIdRoute: AuthenticatedCrmIdRoute,
}

const AuthenticatedCrmRouteWithChildren =
  AuthenticatedCrmRoute._addFileChildren(AuthenticatedCrmRouteChildren)

interface AuthenticatedOsRouteChildren {
  AuthenticatedOsIdRoute: typeof AuthenticatedOsIdRoute
}

const AuthenticatedOsRouteChildren: AuthenticatedOsRouteChildren = {
  AuthenticatedOsIdRoute: AuthenticatedOsIdRoute,
}

const AuthenticatedOsRouteWithChildren = AuthenticatedOsRoute._addFileChildren(
  AuthenticatedOsRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedCaixaRoute: typeof AuthenticatedCaixaRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedFunilRoute: typeof AuthenticatedFunilRoute
  AuthenticatedGuiaRoute: typeof AuthenticatedGuiaRoute
  AuthenticatedHojeRoute: typeof AuthenticatedHojeRoute
  AuthenticatedIaRoute: typeof AuthenticatedIaRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedIntegracoesRoute: typeof AuthenticatedIntegracoesRoute
  AuthenticatedLojaPropriaRoute: typeof AuthenticatedLojaPropriaRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOsRoute: typeof AuthenticatedOsRouteWithChildren
  AuthenticatedPdvRoute: typeof AuthenticatedPdvRoute
  AuthenticatedPlanejamentoRoute: typeof AuthenticatedPlanejamentoRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedSuperAdminRoute: typeof AuthenticatedSuperAdminRoute
  AuthenticatedVendasRoute: typeof AuthenticatedVendasRoute
  AuthenticatedWaConfigRoute: typeof AuthenticatedWaConfigRoute
  AuthenticatedWaInboxRoute: typeof AuthenticatedWaInboxRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedCaixaRoute: AuthenticatedCaixaRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedFunilRoute: AuthenticatedFunilRoute,
  AuthenticatedGuiaRoute: AuthenticatedGuiaRoute,
  AuthenticatedHojeRoute: AuthenticatedHojeRoute,
  AuthenticatedIaRoute: AuthenticatedIaRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedIntegracoesRoute: AuthenticatedIntegracoesRoute,
  AuthenticatedLojaPropriaRoute: AuthenticatedLojaPropriaRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOsRoute: AuthenticatedOsRouteWithChildren,
  AuthenticatedPdvRoute: AuthenticatedPdvRoute,
  AuthenticatedPlanejamentoRoute: AuthenticatedPlanejamentoRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedSuperAdminRoute: AuthenticatedSuperAdminRoute,
  AuthenticatedVendasRoute: AuthenticatedVendasRoute,
  AuthenticatedWaConfigRoute: AuthenticatedWaConfigRoute,
  AuthenticatedWaInboxRoute: AuthenticatedWaInboxRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContatoRoute: ContatoRoute,
  PrecosRoute: PrecosRoute,
  RecursosRoute: RecursosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SegmentosRoute: SegmentosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AgendarSlugRoute: AgendarSlugRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicWaWebhookRoute: ApiPublicWaWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
